kind: PersistentVolume
apiVersion: v1
metadata:
  name: angular-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/angular-app