name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build Angular app
      run: |
        npm install
        npm run build --prod

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/kunbernetes-testing:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/kunbernetes-testing:latest

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/kunbernetes-testing kunbernetes-testing=${{ secrets.DOCKER_USERNAME }}/kubernetes-testing:latest
        kubectl rollout status deployment/kunbernetes-testing
