name: Build and Deploy Angular App to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build Angular app
      run: |
        npm install
        npm run build --prod

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/kubernetes-testing:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/kubernetes-testing:latest

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl set image deployment/kubernetes-testing kubernetes-testing=${{ secrets.DOCKER_USERNAME }}/kubernetes-testing:latest
        kubectl rollout status deployment/kubernetes-testing
